name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-github:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - run: tar -czf gus-mac.tar.gz -C target/release gus
      - run: shasum -a 256 gus-mac.tar.gz
      - uses: softprops/action-gh-release@v2
        with:
          files: gus-mac.tar.gz
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-homebrew:
    runs-on: ubuntu-latest
    needs: [release-github]
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{ secrets.GH_PAT }}
          tap: jamieweavis/homebrew-gus
          formula: gus
          livecheck: true
          no_fork: true
