name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - run: tar -czf gus-mac.tar.gz -C target/release gus
      - uses: softprops/action-gh-release@v2
        with:
          files: gus-mac.tar.gz
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
